For a start to visualizing the data and understanding the attributes we imported pandas and matplotlib

In [17]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings
from xgboost import XGBClassifier
warnings.filterwarnings('ignore')
%matplotlib inline

In [18]:
df = pd.read_csv("application_train.csv")
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
pd.set_option("display.max_seq_items",None)

In [19]:
df.loc[df['FLAG_OWN_CAR'] == 'N', 'OWN_CAR_AGE'] = 0

In [20]:
df['AMT_ANNUITY'] = df['AMT_ANNUITY'].fillna(df['AMT_ANNUITY'].median())
df['AMT_GOODS_PRICE'] = df['AMT_GOODS_PRICE'].fillna(df['AMT_GOODS_PRICE'].mean())
df['EXT_SOURCE_1'] = df['EXT_SOURCE_1'].fillna(df['EXT_SOURCE_1'].mean())
df['EXT_SOURCE_2'] = df['EXT_SOURCE_2'].fillna(df['EXT_SOURCE_2'].mean())
df['EXT_SOURCE_3'] = df['EXT_SOURCE_3'].fillna(df['EXT_SOURCE_3'].mean())

In [21]:
df = df.drop(columns=['APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
       'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG',
       'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG',
       'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG',
       'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE',
       'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE',
       'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE',
       'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI',
       'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
       'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI',
       'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI',
       'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',
       'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE',
       'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'])

In [22]:
df = df.dropna(subset=["OBS_30_CNT_SOCIAL_CIRCLE", "AMT_REQ_CREDIT_BUREAU_HOUR"])

In [23]:
df['OWN_CAR_AGE'] = df['OWN_CAR_AGE'].fillna(0)
df['NAME_TYPE_SUITE'] = df['NAME_TYPE_SUITE'].fillna(df['NAME_TYPE_SUITE'].mode()[0])
df['CNT_FAM_MEMBERS'] = df['CNT_FAM_MEMBERS'].fillna(df['CNT_FAM_MEMBERS'].mode()[0])
df['OCCUPATION_TYPE'] = df['OCCUPATION_TYPE'].fillna("Unknown")
df['DAYS_LAST_PHONE_CHANGE'] = df['DAYS_LAST_PHONE_CHANGE'].fillna(df['DAYS_LAST_PHONE_CHANGE'].mode()[0])

In [24]:
df.head()

SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
4      100007       0         Cash loans           M            N   
5      100008       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
4               Y             0          121500.0    513000.0      21865.5   
5               Y             0           99000.0    490495.5      27517.5   

   AMT_GOODS_PRICE  NAME_TYPE_SUITE NAME_INCOME_TYPE  \
0         351000.0    Unaccompanied          Working   
1        1129500.0           Family    State servant   
2         135000.0    Unaccompanied          Working   
4         513000.0    Unaccompanied          Working   
5         454500.0  Spouse, partner    State servant   

             NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
0  Secondary / secondary special  Single / not married  House / apartment   
1               Higher education               Married  House / apartment   
2  Secondary / secondary special  Single / not married  House / apartment   
4  Secondary / secondary special  Single / not married  House / apartment   
5  Secondary / secondary special               Married  House / apartment   

   REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  \
0                    0.018801       -9461           -637            -3648.0   
1                    0.003541      -16765          -1188            -1186.0   
2                    0.010032      -19046           -225            -4260.0   
4                    0.028663      -19932          -3038            -4311.0   
5                    0.035792      -16941          -1588            -4970.0   

   DAYS_ID_PUBLISH  OWN_CAR_AGE  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  \
0            -2120          0.0           1               1                0   
1             -291          0.0           1               1                0   
2            -2531         26.0           1               1                1   
4            -3458          0.0           1               1                0   
5             -477          0.0           1               1                1   

   FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS  \
0                 1           1           0        Laborers              1.0   
1                 1           1           0      Core staff              2.0   
2                 1           1           0        Laborers              1.0   
4                 1           0           0      Core staff              1.0   
5                 1           1           0        Laborers              2.0   

   REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY  \
0                     2                            2   
1                     1                            1   
2                     2                            2   
4                     2                            2   
5                     2                            2   

  WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  \
0                  WEDNESDAY                       10   
1                     MONDAY                       11   
2                     MONDAY                        9   
4                   THURSDAY                       11   
5                  WEDNESDAY                       16   

   REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  \
0                           0                           0   
1                           0                           0   
2                  

In [25]:
df = df.drop(columns=['SK_ID_CURR'])

In [26]:
df.shape

(265141, 74)

In [27]:
for i in df.columns:
    if not pd.api.types.is_numeric_dtype(df[i]):  # Check for non-numeric type
        df[i] = LabelEncoder().fit_transform(df[i])

In [28]:
X = df.drop(columns=['TARGET'])
y = df['TARGET']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.1, random_state=42)

In [29]:
ros = RandomOverSampler(random_state=42)  # Or other oversampling methods
X_rostrain, y_rostrain = ros.fit_resample(X_train, y_train)

In [30]:
rus = RandomUnderSampler(random_state=42)  # Or other undersampling methods
X_rustrain, y_rustrain = rus.fit_resample(X_train, y_train)

In [31]:
lr = LogisticRegression(max_iter=100000, n_jobs=-1, class_weight={1:10, 0:1})

In [32]:
lr.fit(X_train, y_train)
y_pred = lr.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.79      0.86     24418
           1       0.12      0.34      0.18      2097

    accuracy                           0.76     26515
   macro avg       0.53      0.57      0.52     26515
weighted avg       0.87      0.76      0.81     26515

[[19406  5012]
 [ 1385   712]]


In [33]:
xgb = XGBClassifier(n_estimators=1000, n_jobs=-1, learning_rate=0.1, random_state=42, class_weight={1:10, 0:1}, eval_metric='auc', max_depth=100)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.92      1.00      0.96     24418
           1       0.45      0.03      0.05      2097

    accuracy                           0.92     26515
   macro avg       0.68      0.51      0.50     26515
weighted avg       0.88      0.92      0.89     26515

[[24352    66]
 [ 2044    53]]


In [34]:
dtn = DecisionTreeClassifier()
dtn.fit(X_train, y_train)
y_pred = dtn.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92     24418
           1       0.16      0.18      0.17      2097

    accuracy                           0.86     26515
   macro avg       0.54      0.55      0.55     26515
weighted avg       0.87      0.86      0.86     26515

[[22426  1992]
 [ 1719   378]]


In [35]:
dto = DecisionTreeClassifier()
dto.fit(X_rostrain, y_rostrain)
y_dtrospred = dto.predict(X_val)
print(classification_report(y_val, y_dtrospred))
print(confusion_matrix(y_val, y_dtrospred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93     24418
           1       0.15      0.16      0.15      2097

    accuracy                           0.86     26515
   macro avg       0.54      0.54      0.54     26515
weighted avg       0.87      0.86      0.87     26515

[[22598  1820]
 [ 1770   327]]


In [36]:
dtu = DecisionTreeClassifier()
dtu.fit(X_rustrain, y_rustrain)
y_pred = dtu.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.58      0.72     24418
           1       0.11      0.59      0.18      2097

    accuracy                           0.58     26515
   macro avg       0.53      0.59      0.45     26515
weighted avg       0.88      0.58      0.68     26515

[[14194 10224]
 [  858  1239]]


In [37]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(X_rustrain, y_rustrain)
y_pred = nb.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.52      0.67     24418
           1       0.10      0.63      0.18      2097

    accuracy                           0.53     26515
   macro avg       0.52      0.58      0.42     26515
weighted avg       0.88      0.53      0.63     26515

[[12738 11680]
 [  766  1331]]


In [38]:
rf = RandomForestClassifier(n_estimators=1000, n_jobs=-1, class_weight={1:10, 0:1}, max_depth=3)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_val)
print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.86      0.90     24418
           1       0.22      0.45      0.29      2097

    accuracy                           0.83     26515
   macro avg       0.58      0.66      0.60     26515
weighted avg       0.89      0.83      0.85     26515

[[21037  3381]
 [ 1153   944]]


In [39]:
# svm = SVC()
# svm.fit(X_rustrain, y_rustrain)
# y_pred = svm.predict(X_val)
# print(classification_report(y_val, y_pred))
# print(confusion_matrix(y_val, y_pred))